GET http://localhost:8080/health
Accept: application/json

###
POST http://localhost:8080/health
Accept: application/json

###

GET http://localhost:8080/hello
Accept: application/json

###
GET http://localhost:8080/hello/
Accept: application/json

###
GET http://localhost:8080/headers
Accept: application/json

###
GET http://localhost:8080/headers/
Accept: application/json

###
GET http://localhost:8080/hello/
Accept: application/json

###
GET http://localhost:8080/badEndpoint/
Accept: application/json
